apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: {{ template "guestbookapplication.name" . }}
spec:
  ports:
    - port: 80
      targetPort: 9370
      protocol: TCP
      name: http
  selector:
    app: {{ template "guestbookapplication.name" . }}
