---
apiVersion: v1
kind: Namespace
metadata:
  name: helmrelease-secret-test
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: kubernetes.io/basic-auth
data:
  user: dXNlcg==
  password: cmVkaGF0
---
apiVersion: apps.open-cluster-management.io/v1
kind: HelmRelease
metadata:
  name: guestbook
  namespace: helmrelease-secret-test
repo:
  chartName: nginx-chart
  source:
    helmRepo:
      urls:
        - http://10.73.72.41/helmreleaseAPItest/nginx-chart-0.1.0.tgz
    type: helmrepo
  version: 0.1.0
  secretRef:
    name: secret-basic-auth
    namespace: helmrelease-secret-test
